# Generated by Django 4.0.2 on 2022-05-27 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 5, 27, 14, 53, 51, 71976))),
                ('todo_date', models.DateTimeField()),
            ],
        ),
    ]
